export const architektura = {
    1: "Projekt koncepcyjny a projekt budowlany; omów ich zakres oraz rolę w procesie projektowym",
    2: "Podaj jedną z definicji „architektury” oraz nazwisko jej autora. Omów tę definicję",
    3: "Cechy architektury według Witruwiusza; omów ich aktualnośd na wybranym przykładzie",
    4: "Przedstaw trzech wybranych znaczących twórców i teoretyków architektury XX/XXI wieku",
    5: "\"Architektura parametryczna”; definicja pojęcia, percepcja zjawiska i przykłady realizacji",
    6: "Zasady zrównoważonego rozwoju i ich wpływ na projektowanie budynków",
    7: "Wpływ nowoczesnych technologii na kształtowanie formy architektonicznej budynku; omów na wybranym przykładzie",
    8: "Funkcja budynku a rozwiązania proekologiczne, omów zagadnienie na wybranym przykładzie",
    9: "Zagadnienia ewakuacji ludzi z obiektów użyteczności publicznej; ewakuacja z obiektów wysokich i wysokościowych. Analiza zagadnienia w oparciu o obowiązujące przepisy",
    10: "Zagadnienia bezpieczeostwa pożarowego budynków w skali architektonicznej i urbanistycznej",
    11: "Funkcja mieszkalna w obiektach poprzemysłowych, omów wady i zalety. Przykłady realizacji w Polsce i na świecie",
    12: "Funkcja biurowa i usługowa w obiektach poprzemysłowych, omów wady i zalety. Przykłady realizacji w Polsce i na świecie",
    13: "Wpływ środowiska przyrodniczego na lokalizację budynku i na decyzje projektowe.Wpływ inwestycji na zmiany w środowisku",
    14: "Ocena cyklu życiowego budynku (i jego faz) jako kryterium proekologicznego doboru materiałów, konstrukcji i technologii wykonawstwa",
    15: "Inspiracje budownictwem regionalnym a najnowsze trendy w architekturze. Omów na wybranym przykładzie",
    16: "Nowoczesne muzeum w mieście, omów przykłady wybranych rozwiązań",
    17: "Podaj 3 przykłady obiektów pływających, które zostały umieszczone na terenach poprzemysłowych w celu ożywienia i uatrakcyjnienia tych przestrzeni. Krótko scharakteryzuj te obiekty",
    18: "Projektowanie uniwersalne; definicja pojęcia i główne założenia w kształtowaniu środowiska zbudowanego",
    19: "Zasady projektowania uniwersalnego; omów min. 2 zasady i sposób ich realizacji w projektowaniu",
    20: "Omów rozwiązania zwiększające bezpieczeostwo ewakuacji osób z ograniczoną sprawnością ruchową i sensoryczną i ich wpływ na architekturę",
    21: "Warunki uzyskania certyfikatu środowiskowego LEED i WELL dla budynku",
    22: "Co to jest zaśmiecenie światłem atmosfery ziemskiej. Co może zrobid architekt/urbanista, aby jego projekty nie przyczyniły się do zwiększenia tego zaśmiecenia?",
    23: "Czym jest architektura kinematyczna? Wymień rodzaje ruchu stosowanego w architekturze",
    24: "Wymień i omów rodzaje cyfrowej fabrykacji",
    25: "Wymień obiekt, który uzyskał certyfikat LEED-BD+C Platinum i wypunktuj rozwiązania, które się do tego przyczyniły",
    26: "Wymień 3 wybrane obiekty, które można zaliczyd do nurtu zielonej architektury (ang. green architecture). Krótko scharakteryzuj jeden z tych obiektów wskazując na proekologiczne rozwiązania",
    27: "Wymień trzy obiekty, w których forma architektoniczna powiązana jest z wodą, wskazując na decyzje projektowe przyjęcia takich rozwiązań",
    28: "Sklasyfikuj obiekty pływające ze względu na rodzaj rozwiązania technicznego umożliwiającego pływalność",
    29: "Wymień korzyści wynikające z projektowania algorytmicznego",
    30: "Wymień i opisz 3 obiekty zaprojektowane dzięki zastosowaniu technik projektowania komutacyjnego",
    31: "Omów problemy związane z adaptacją budynków poprzemysłowych na nowe funkcje na podstawie dwóch przykładów",
    32: "Podaj jakie opracowania branżowe należy wykonad przed przystąpieniem do koncepcji architektonicznej adaptacji obiektów zabytkowych do nowej funkcji. Podaj przynajmniej trzy",
    33: "Czym jest rewitalizacja? Podaj przykłady trzy z Polski i trzy z zagranicy",
    34: "Czy prawidłowym jest sformułowanie \"rewitalizacja obiektu architektonicznego\"? Swoją odpowiedź umotywuj korzystając z definicji rewitalizacji i celów strefy ochrony konserwatorskiej",
}