export const historiaArchitektury = {
    1: "Dekonstruktywizm w architekturze; cechy charakterystyczne, najważniejsi twórcy i realizacje",
    2: "Architektura „Bauhausu”; charakterystyka, przykłady",
    3: "Konstruktywizm w architekturze; zasady, geneza, reprezentanci",
    4: "Socrealizm w architekturze; geneza, cechy charakterystyczne, przykłady realizacji",
    5: "Ekspresjonizm w architekturze; charakterystyka, przykłady",
    6: "Minimalizm w architekturze; charakterystyka, przykłady",
    7: "Główne nurty historyczne architektury starożytnej; nazwy, chronologia, przykłady i charakterystyczne cechy stylowe",
    8: "Główne nurty historyczne architektury średniowiecza; nazwy, chronologia, przykłady i charakterystyczne cechy stylowe",
    9: "Główne nurty historyczne architektury nowożytnej do kooca XIX wieku; nazwy, chronologia, przykłady i charakterystyczne cechy stylowe",
    10: "Dojrzały modernizm powojenny w architekturze; charakterystyka, przykłady",
    11: "Definicje pojęd: „reintegracja zabytku” i „odbudowa zabytku”",
    12: "Różnice w podejściu do problemów odbudowy po zniszczeniach II wojny światowej na przykładzie Warszawy i Gdaoska",
    13: "Forma monumentalna w architekturze starożytnej; zasady kompozycyjne kształtowania",
    14: "Formy historyczne w architekturze postmodernizmu; przykłady interpretacji",
    15: "Definicje pojęd: „dziedzictwo kultury”, „dobro kultury”, „zabytek”",
    16: "Definicja pojęd: „konserwacja zabytku” i „restauracja zabytku”",
    17: "Definicja pojęcia „rekonstrukcja zabytku” i warunki techniczne umożliwiające jej przeprowadzenie",
    18: "Historyzm w architekturze europejskiej – czas trwania, twórcy, dzieła",
    19: "Polskie awangardowe ugrupowania architektoniczno-artystyczne okresu międzywojennego – twórcy, działalnośd, osiągnięcia",
    20: "Forma „klasyczna” i „klasycyzm” w architekturze – geneza oraz interpretacje stylowe na przestrzeni wieków",
    21: "Wyjaśnij skrót CIAM, podaj nazwiska pięciu najbardziej znanych członków tej organizacji i scharakteryzuj jej działalnośd",
    22: "Definicje pojęd: „anastyloza” i „rekonstrukcja”. Warunki techniczne konieczne do przeprowadzenia ww. działao",
    23: "Dekoracje malarskie i tynkarskie kamienic gdaoskich odbudowanych po II wojnie światowej",
    24: "Architektura polska okresu międzywojennego - główne kierunki stylowe, dzieła, architekci",
    25: "Omów architekturę historycznego kampusu Politechniki Gdaoskiej i jej wzorce",
    26: "Czym jest sztuka per formatywna?",
    27: "Jakie jest znaczenie pojęcia awangarda w sztuce?",
    28: "Wyjaśnij czy piękno to jedyna kategoria sztuki współczesnej?",
    29: "Co oznacza termin Kamp w sztuce?",
    30: "Sztuka i pamięd; omówid problematykę pamięci na wybranych przykładach",
    31: "Czy istnieje definicja pojęcia sztuki i dzieła sztuki? Wyjaśnij problematykę",
    32: "Jakie są w Twojej opinii przełomowe dzieła sztuki i dlaczego",
}