export const technika = {
1: "Usystematyzuj rozwiązania materiałowe dla fasad budynków. Omów jeden wybrany przykład",
2: "Rodzaje szkła stosowane współcześnie ze względu na ochronę przeciwsłoneczną, cieplną, bezpieczeostwo i efekty wizualne. Omów wybrany przykład zastosowania szkła w budynku",
3: "Wymień źródła ogrzewania budynku. Opisz wybrany przykład",
4: "Opisz sposoby wentylacji pomieszczeo w budynkach. Jak wybór sposobu wentylacji wpływa na kształtowanie rozwiązao architektonicznych?",
5: "Porównaj założenia projektowe dla budynków energooszczędnych i pasywnych",
6: "Posadowienie budynku w trudnych warunkach gruntowych. Omów jeden z przykładów posadowienia: na skarpie, na terenach słabonośnych, w zabudowie plombowej",
7: "Posadowienie budynku poniżej poziomu wód gruntowych. Omów rozwiązania w kontekście konstrukcji i izolacji przeciwwodnej",
8: "Co to jest ekspertyza techniczna budynku. Kto i w jakim celu ją wykonuje?",
9: "Przekrycia sal widowiskowych, sportowych, basenów. Zaproponuj rozwiązania konstrukcji jednej z nich",
10: "Kształtowanie ustrojów nośnych hal. Wymień podstawowe elementy hali i podaj funkcję jaką spełniają",
11: "Opisz zasadę działania stropów żelbetowych z płyt sprężonych. Dla jakich rozpiętości mają zastosowanie?",
12: "Stropy żelbetowe w budynku o konstrukcji typu płyta-słup. Omów założenia do projektowania takich obiektów. Jakie parametry i naprężenia decydują o przekroju słupa środkowego?",
13: "Charakterystyka stropów płytowo-ryglowych. Omów pracę rygla w kontekście wytrzymałości materiałów (rodzaje naprężeo, optymalizacja przekroju, itp.)",
14: "Ruszt jako ustrój konstrukcyjny. Omów zagadnienie i podaj przykłady rozwiązao",
15: "Budynki wysokie i wysokościowe. Omów rozwiązania ustroju konstrukcyjnego w odniesieniu do wysokości budynków",
16: "Omów zagadnienie stateczności obiektu. Jakie parametry i elementy budynku odpowiadają za sztywnośd przestrzenną?",
17: "Dylatacje w konstrukcjach budowlanych i jej wpływ na kształtowanie architektury budynku. Jakie zagrożenia wynikają z braku dylatacji?",
18: "Powłoki – definicja, istota pracy, szkice. Podaj przykłady realizacji",
19: "Wyjaśnid istotę betonowych konstrukcji sprężonych. Podaj przykłady rozwiązao ustrojów",
20: "Wyjaśnid różnicę w pracy statycznej kratownicy płaskiej i kratownicy przestrzennej",
21: "Dachowe konstrukcje wiszące. Definicja, podziały, przykłady realizacji",
22: "Charakterystyka energetyczna budynku. Podaj czynniki wpływające na zapotrzebowanie energetyczne. Odnieś się do aktualnych wymagao",
23: "Ochrona cieplna budynku: aktualne wymagania i ogólne zasady projektowania przegród",
24: "Podstawowe zasady projektowania przegród nieprzezroczystych w budynku, ze względu na ryzyko kondensacji",
25: "Mostek cieplny; definicja pojęcia, klasyfikacja i przykłady występowania mostków w budynkach. Opisz wybrany przykład zminimalizowania mostka cieplnego",
}