export const urbanistyka = {
1: "Koncepcje pionierów urbanistyki XX wieku i ich znaczenie dla rozwoju współczesnego miasta",
2: "Koncepcje \„miasta liniowego\", \„miasta-ogrodu\", \„miasta przemysłowego\" i ich znaczenie we współczesnej urbanistyce",
3: "Podstawowe zasady zrównoważonego rozwoju i ich stosowanie w kształtowaniu struktury miasta",
4: "Pojęcie „miasta kompaktowego” i jego główne cechy",
5: "Główne problemy związane z procesami suburbanizacji",
6: "Opracowania planistyczne na szczeblu gminy i ich rola w kształtowaniu architektury i urbanistyki",
7: "Pojęcie polityki przestrzennej gminy",
8: "Podstawowe rodzaje dokumentów planistycznych funkcjonujących w polskim systemie prawnym",
9: "Dokumenty planistyczne na szczeblu regionalnym",
10: "Podstawy prawne kształtowania polityki przestrzennej gminy",
11: "Podstawowe elementy struktury przestrzennej określane w dokumentach planistycznych",
12: "Podstawowe rodzaje linii regulacyjnych, stosowanych w dokumentach planistycznych",
13: "Instytucje uczestniczące w procedurze planistycznej dotyczącej miejscowego planu zagospodarowania przestrzennego",
14: "Podstawowe rodzaje działao związanych z odnową struktur miejskich – na wybranych przykładach",
15: "Pojęcie rewitalizacji miasta",
16: "Rodzaje działao związanych z kompleksową rewitalizacją miast",
17: "Główne typy działao składających się na procesy rewitalizacji miasta",
18: "Rola partycypacji społecznej w planowaniu współczesnego miasta",
19: "Sposoby zapewniania udziału społeczności lokalnej w procesie podejmowania decyzji przestrzennych",
20: "Planowanie procesów odnowy współczesnego miasta",
21: "Podstawowe rodzaje degradacji struktur miejskich",
22: "Problemy odnowy obszarów mieszkaniowych",
23: "Problemy odnowy obszarów poportowych i poprzemysłowych",
24: "Problemy odnowy obszarów śródmiejskich",
25: "Podstawowe zasady kształtowania zespołów śródmiejskich",
26: "Strategia rozwoju gminy – elementy, znaczenie i sposoby określania",
27: "Znaczenie dziedzictwa w procesach rewitalizacji i odnowy struktur miejskich",
28: "Ekonomika procesów odnowy i rewitalizacji struktur miejskich",
29: "Tematyzacja przestrzeni publicznej – pojęcie, główne wyzwania",
30: "Przedsięwzięcia urbanistyczne o charakterze wielkoskalowym – pojęcie, wybrane przykłady",
}